### ISSUE TITLE
lost focus when AlwaysShadow  is running 

### ISSUE THREAD

**Issue by zino73** [Verpous/AlwaysShadow#16] opened 2024-04-05 17:02 UTC
when something trunoof shadowplay and AlwaysShadow do his thing, i loose the focus on the application im using it (and its very anoying when im writing in a chat appliction like MS teams or Slack or somehting else) is there somthing to do to avoid this?

**Comment by Verpous** [comment] 2024-04-05 17:36
That's odd, it's not supposed to happen. If you aren't using the latest version, please download it and try again. If it still happens, give me more details like:
* Which application is closing shadowplay?
* Is the application you're losing focus on the same application or a different one?
* Please drop in the logs file `%LOCALAPPDATA%/AlwaysShadow/output.log`

**Comment by zino73** [comment] 2024-04-05 17:53
Which application is closing shadowplay? - MS TEAMS when i share my screen and when i get a notification or when MS teams is minimize the return cam.
Is the application you're losing focus on the same application or a different one? the same Teams as well 
Please drop in the logs file %LOCALAPPDATA%/AlwaysShadow/output.log : done 

[output.log](https://github.com/Verpous/AlwaysShadow/files/14889040/output.log)

**Comment by Verpous** [comment] 2024-04-05 19:52
I don't see any errors your logs and from my testing with other programs which turn off Shadowplay I can't reproduce this issue. So I think this issue is specific to Teams, and it's not AlwaysShadow stealing focus when it toggles Shadowplay on, but Teams for some reason relinquishing focus when it toggles it off. I don't know how much I can do about that.

I see from the logs that you don't have a whitelist. You can whitelist teams to avoid this issue, but if you like to have teams open 
in the background all the time then that'd a problem.

Sorry!

**Comment by zino73** [comment] 2024-04-05 21:07
ok thanks , Teams seems doing a lot of bugs with Shadowplay and i cant fix it for now this is why im installed and using AlwaysShadow thanks for your help.

**Closed** 2024-04-05 21:07 UTC
